// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/6/2025, 3:05:45 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/afarooq/Documents/Projects/sozetaleem/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/afarooq/Documents/Projects/sozetaleem/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/afarooq/Documents/Projects/sozetaleem/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/afarooq/Documents/Projects/sozetaleem/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/afarooq/Documents/Projects/sozetaleem/frontend/plugins/**/*.{js,ts,mjs}","/Users/afarooq/Documents/Projects/sozetaleem/frontend/composables/**/*.{js,ts,mjs}","/Users/afarooq/Documents/Projects/sozetaleem/frontend/utils/**/*.{js,ts,mjs}","/Users/afarooq/Documents/Projects/sozetaleem/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/afarooq/Documents/Projects/sozetaleem/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/afarooq/Documents/Projects/sozetaleem/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/afarooq/Documents/Projects/sozetaleem/frontend/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;